config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"
  resources :users, except: :index 
  delete '/user/delete', to: 'users#destroy'
  get '/signin', to: 'sessions#new'
  get '/auth/facebook/callback' => 'sessions#facebook'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/landlord.rb
class Landlord < ApplicationRecord
    has_one :user, as: :userable
    has_many :properties
    validates :first_name, :last_name,  presence: true
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :landlord
    has_many :reviews
    has_many :tenants, through: :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :tenant
    belongs_to :property
end

app/models/tenant.rb
class Tenant < ApplicationRecord
    has_one :user, as: :userable
    has_many :reviews
    has_many :properties, through: :reviews
    validates :first_name,   presence: true
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :userable, polymorphic: true
    has_secure_password
    validates :email, uniqueness: true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?
    
    def current_user
        @user = User.find_by(id: session[:user_id])
    end
      
    def set_session
        session[:user_id] = @user.id
    end
    
    def logged_in?
        !current_user.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   
    def new
    end
   
    def create
      @user = User.find_by(:email => params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:notice] = "Invalid Email or Password. Please try agin."
        render :new
      end
    end
    
    def facebook
      # @tenant = Tenant.find_or_create_by(email: auth['info']['email']) do |t|
      #   t.build_user(first_name: auth['info']['name'], password: SecureRandom.hex)
      # end

      # @user = User.find_or_create_by(uid: auth['uid']) do |u|
      #   u.email = auth['info']['email']
      #   u.password = SecureRandom.hex
      #   u.userable = "Tenant"
        
      # end


      @tenant = Tenant.create(first_name: auth['info']['name'])
      @user = @tenant.build_user(email: auth['info']['email'], password: SecureRandom.hex)
      set_session
      byebug
      redirect_to user_path(@user)
    end

    def destroy
      if current_user
        session.delete :user_id
        redirect_to root_url
      end
    end

    private
 
    def auth
      request.env['omniauth.auth']
    end
    
  end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in?, :current_user, :set_userable, except: [:new, :create]

    def new
    end

    def create
        if params[:landlord] == "0"
            @tenant = Tenant.new(userable_params)
            if @tenant.valid?
                @tenant.save
                @user = @tenant.build_user(user_params)
                if @user.valid?
                    @user.save
                    set_session
                    redirect_to user_path(@user)
                else
                    render :new
                end
            else
                render :new
            end
        else
            @landlord = Landlord.new(userable_params)
            if @landlord.valid?
                @landlord.save
                @user = @landlord.build_user(user_params)
                if @user.valid?
                    @user.save
                    set_session
                    redirect_to user_path(@user)
                else
                    render :new
                end
            else
                render :new
            end
        end
    end

    def show
    end
    
    def edit 
    end

    def update
        if @user.userable_type == "Tenant"
            if @tenant.update(userable_params)
                @tenant.save
                redirect_to @user
            else
                render :edit
            end
        elsif @user.userable_type == "Landlord"
            if @landlord.update(userable_params)
                @landlord.save
                redirect_to @user
            else
                render :edit
            end
        else 
            render :edit
        end
    end

    def destroy
        if @tenant
            @tenant.destroy
            current_user.destroy
        else
            @landlord.destroy
            current_user.destroy
        end
        redirect_to root_path
    end

    private

    def user_params
        params.permit(:email, :password)
    end

    def userable_params
        params.permit(:first_name, :last_name, :age, :about)
    end
    
    def set_userable
        if @user.userable_type == "Tenant"
            @tenant = Tenant.find_by(id: @user.userable_id)
        else
            @landlord = Landlord.find_by(id: @user.userable_id)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentersReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
  <footer>

  <% if logged_in? %>
    <%= link_to "Log out", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Sign In", signin_path %>
  <% end %>
  </footer>
</html>

app/views/users/edit.html.erb
<center><h3> Edit User: </h3></center>
<% if @landlord %>
    <%= form_tag user_path(@user), method: "put" do %>
        <label>First Name:</label><br>
        <%= text_field_tag :first_name, @landlord.first_name %><br>
        <br>
        <label>Last Name:</label><br>
        <%= text_field_tag :last_name, @landlord.last_name %><br>
        <br>
        <label>Age:</label><br>
        <%= text_field_tag :age, @landlord.age %><br>
        <br>
        <label>About:</label><br>
        <%= text_area_tag :about, @landlord.about %><br>

        <%= submit_tag "Submit Edit" %>
    <% end %>
    <p> Do you wish to <%= link_to "delete your account?", user_delete_path(@user), method: "delete" %></p>
    <p> Warning, once this is done, you will have to sign up again. </p>
<% else %>
    <% @tenant %>
    <%= form_tag user_path(@user), method: "put" do %>
        <label>First Name:</label><br>
        <%= text_field_tag :first_name, @tenant.first_name %><br>
        <br>
        <label>Last Name:</label><br>
        <%= text_field_tag :last_name, @tenant.last_name %><br>
        <br>
        <label>Age:</label><br>
        <%= text_field_tag :age, @tenant.age %><br>
        <br>
        <label>About:</label><br>
        <%= text_area_tag :about, @tenant.about %><br>

        <%= submit_tag "Submit Edit" %>
    <% end %>
    <p> Do you wish to <%= link_to "delete your account?", user_delete_path(@user), method: "delete" %></p>
    <p> Warning, once this is done, you will have to sign up again. </p>
<% end %>

<% if !@tenant.nil? && @tenant.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@tenant.errors.count, "error") %>
      prohibited this user from being created:
    </h2>
 
    <ul>
    <% @tenant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if !@landlord.nil? && @landlord.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@landlord.errors.count, "error") %>
      prohibited this user from being created:
    </h2>
 
    <ul>
    <% @landlord.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
 <center><h3> New User Sign Up: </h3></center>

    <%= form_with url:'/users', local: :true do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email  %>
        <br>  
        <%= f.label :password %>
        <%= f.password_field :password %>
        <br>
        <%= f.label "First Name" %>
        <%= f.text_field :first_name  %>
        <br>
        <%= f.label "Last_name" %>
        <%= f.text_field :last_name %>
        <br>
        <%= f.label :age %>
        <%= f.text_field :age %>
        <br>
        <%= f.label :about %>
        <%= f.text_area :about %>
        <br>
        <%= f.label "Check the box if you wish to sign up as a Landlord" %>
        <%= f.check_box "landlord" %>
     


      <span class="pull-left"><%= f.submit "Create New User"  %></span>
   <% end %>

<% if !@user.nil? && @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being created:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if !@tenant.nil? && @tenant.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@tenant.errors.count, "error") %>
      prohibited this user from being created:
    </h2>
 
    <ul>
    <% @tenant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if !@landlord.nil? && @landlord.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@landlord.errors.count, "error") %>
      prohibited this user from being created:
    </h2>
 
    <ul>
    <% @landlord.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<h1> User Show Page </h1>

<%if @landlord %>
    <p> You are a listed as a Landlord.</p>
    <p> First Name: <%=@landlord.first_name%> </p>
    <p> Last name: <%=@landlord.last_name%> </p>
    <p> Age: <%=@landlord.age%> </p>
    <p> About: <%=@landlord.about%> </p>
<%else %>
    <p> You are a listed as a Tenant.</p>
    <p> First Name: <%=@tenant.first_name%> </p>
    <p> Last name: <%=@tenant.last_name%> </p>
    <p> Age: <%=@tenant.age%> </p>
    <p> About: <%=@tenant.about%> </p>
<% end %>
<p>Email: <%=@user.email%></p>

<p> Would you like to <%= link_to "Edit", edit_user_path(@user)%> your profile?</p>